version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: order-manager
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: order-manager
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/order-manager
    depends_on:
      - mongo

volumes:
  mongo-data:
